version: '3'
services:
  db:
    image: 'postgres:lastest'
    environment: 
      POSTGRES_PASSWORD=945332002Af*
      POSTGRES_USER=postgres
      POSTGRES_DB=sendreport_db
    volumes:
     - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
